---
title: "day0620"
output: html_document
date: '2022-06-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
TRUE OR FALSE
```{r}
logical_vector<-c(TRUE,FALSE)
logical_vector

```
Character
```{r}
char_vector<-c("hi","hello")
char_vector
```
About Factor
```{r}
# 명목형 자료형 Factor
locaiton_vector <- c("서울", "인천", "부산")
factor_location_vector <- factor(locaiton_vector)
factor_location_vector

class(factor_location_vector)
help(factor)

# 순서형 자료형 Factor
temperature_factor <- c("기온높음", 
                        "기온보통", 
                        "기온낮음", 
                        "기온높음", 
                        "기온보통", 
                        "기온보통")

temperature_factor

factor_temperature_factor <- factor(temperature_factor, 
                                    ordered = TRUE, 
                                    levels  = c("기온보통", 
                                                "기온낮음", 
                                                "기온높음"))
factor_temperature_factor

```

데이터 프레임 만들기
```{r}
sex<-c("male","female")
korean<-c(72,83)
english<-c(99,31)

exam_a<-data.frame(sex,korean,english)
exam_a
```
str 사용하기
```{r}
str(exam_a)
```


